Cafe/Cafe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    # The path below does when the user hits the '/' which is root redirect to '/cafe_order/'
    path('', lambda req: redirect('/cafe_order/')),
    path('cafe_order/', include('cafe_order.urls')),
    path('admin/', admin.site.urls),
]

Cafe/cafe_order/urls.py
from distutils.sysconfig import customize_compiler
from django.urls import path 
from . import views

app_name = 'cafe_order'
urlpatterns = [
    path('', views.welcome,name='root'),
    path('register/', views.customer_register,name='register'),
    path('login/', views.customer_login, name='login'),
    path('home/', views.customer_home, name='home'),
    path('logout/', views.customer_logout, name = 'logout'),
    path('create_order/<str:id>/', views.create_order, name="create_order"),
    path('list_orders/', views.list_orders, name = "list_orders"),
    path('delete_food/<str:id>/',views.delete_food, name = "delete_food"),
    path('confirm_order/<str:id>/', views.confirm_order, name = 'confirm_order'),
    path('confirmed_order/', views.confirmed_order, name = 'confirmed_order'),
    path('list_confirmed_orders/', views.list_confirmed_orders, name='list_confirmed_orders')
]

Cafe/cafe_order/models.py
from xml.parsers.expat import model
from django.db import models


class Customer(models.Model):
    customer_username = models.CharField(max_length=254)
    customer_name_surname = models.CharField(max_length=128)
    customer_email = models.EmailField(max_length=254)
    customer_password = models.CharField(max_length=120)

    def __str__(self) -> str:
        return self.customer_email

class Foods(models.Model):
    food_name = models.CharField(max_length=128)
    food_description = models.CharField(max_length=512)
    food_price = models.FloatField()

    def __str__(self) -> str:
        return self.food_name

class Order(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Delivery is taken', 'Delivery is taken'),
        ('Out for delivery', 'Out for delivery'),
        ('Delivered', 'Delivered'),
        )
    customer_id = models.ForeignKey(Customer, on_delete=models.DO_NOTHING)
    order_recieved_date = models.DateTimeField()
    order_status = models.CharField(max_length=64, choices=STATUS)

class OrderFoods(models.Model):
    order_id = models.ForeignKey(Order,on_delete=models.CASCADE)
    food_id = models.ForeignKey(Foods,on_delete=models.DO_NOTHING)

Cafe/cafe_order/forms.py
from django import forms
from .models import Customer

class CustomerRegisterInForm(forms.ModelForm):
    customer_password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = Customer
        fields = ['customer_name_surname', 'customer_email', 'customer_password']

class CustomerLoginForm(forms.ModelForm):
    customer_password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = Customer
        fields = ['customer_email', 'customer_password']
        

Cafe/cafe_order/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, HttpResponse, redirect
from .forms import CustomerLoginForm, CustomerRegisterInForm
from .models import Customer, Foods, Order, OrderFoods
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .utils import utils
from django.contrib.auth.models import User
import datetime
from django.db.models import Avg, Count, Min, Max, Sum
from django import template



def welcome(request):
    return render(request, 'cafe_order/welcome.html')

# This view renders a registration form
# The view controls the is user already in database or not
# And also user both saved on Customer model and django admin's user model
def customer_register(request):
    if request.method == 'POST':
        form = CustomerRegisterInForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['customer_email']
            
            if Customer.objects.filter(customer_email=email).exists():
                user = form.cleaned_data.get('customer_name_surname')
                messages.info(
                    request, 'User already exists! Try logging in.')
                return redirect('cafe_order:login')
            else:
                customer={
                    'customer_email':form['customer_email'].value(),
                    'customer_username':utils.create_user_name(form['customer_email'].value()),
                    'customer_password':form['customer_password'].value(),
                    'customer_name_surname':form['customer_name_surname'].value()
                }
                customer_model = Customer(**customer)
                customer_model.save()
                user = User.objects.create_user(first_name = customer['customer_name_surname'], username = customer['customer_username'], password = customer['customer_password'],email=customer['customer_email'])
                user.is_active = True
                user.save()
                return redirect('cafe_order:login')
    else:
        form = CustomerRegisterInForm()
    context = {
        'form':form
    }
    return render(request, "cafe_order/customer_register.html", context)


# This view renders a login form
# with help of authenticate function users get in
def customer_login(request):
    if request.user.is_authenticated:
        return redirect('cafe_order:home')
    else:
        if request.method == 'POST':
            form = CustomerLoginForm(request.POST)
            if form.is_valid():

                password = form.cleaned_data['customer_password']
                user = authenticate(request, username = utils.create_user_name(form['customer_email'].value()), password=password)
                if user is not None:
                    login(request, user)
                    return redirect('cafe_order:home')
                else:
                    return redirect('cafe_order:login')
        else: 
            form = CustomerLoginForm()
        context = {
            'form': form
        }
        return render(request, 'cafe_order/customer_login.html', context)

# This views where the customer pick foods in other words items into cart 
@login_required(login_url='cafe_order:login')
def customer_home(request):
    foods = Foods.objects.all()
    context = {'foods': foods}
    return render(request, 'cafe_order/customer_home.html',context=context)

# This helps logout the customer
# Customer session lifetime is already controlled by SessionIdleTimeout which is in Cafe/middleware.py
@login_required(login_url='cafe_order:login')
def customer_logout(request):
    logout(request)
    return redirect('cafe_order:login')

# when user add an food on cart it creates a order until confirms her order item will added on that created order 
@login_required(login_url='cafe_order:login')
def create_order(request,id):
    customer =  Customer.objects.filter(customer_email__iregex=f'{request.user}+@.+')[0]
    filtered_order = Order.objects.filter(customer_id = customer.id, order_status = Order.STATUS[0][0])
    if filtered_order.exists():
        food_list = OrderFoods(order_id = filtered_order[0], food_id = Foods.objects.get(id=int(id)))
        food_list.save()
    else:
        order = Order(
                customer_id = customer,
                order_recieved_date = datetime.datetime.utcnow(), 
                order_status = Order.STATUS[0][0]
            )
        order.save()
        food_list = OrderFoods(order_id = order, food_id = Foods.objects.get(id=int(id)))
        food_list.save()
    return redirect('cafe_order:home')

# This views render the customer's current active cart
@login_required(login_url='cafe_order:login')
def list_orders(request):

    order_foods = OrderFoods.objects.filter(order_id__customer_id=Customer.objects.get(customer_email__iregex=f'{request.user}+@.+'),
                                            order_id__order_status = Order.STATUS[0][0]                                         
                                            ).select_related('order_id','food_id')

    order = Order.objects.filter(customer_id=Customer.objects.get(customer_email__iregex=f'{request.user}+@.+'),order_status = Order.STATUS[0][0] )
    if order:
        context = {
            'order_id': order[0].id,
            'order_foods':order_foods,

        }
    else:
        context = {
            'order_foods':order_foods,
            'order_id' : None
        }
    return render(request, 'cafe_order/customer_active_orders.html',context=context)

# Customer can remove the foods from cart before she confirms
@login_required(login_url='cafe_order:login')
def delete_food(request, id):
    OrderFoods.objects.filter(id=id).delete()

    #return redirect('cafe_order:list_orders')
    return redirect(request.META.get('HTTP_REFERER'))

# Customer confirms the current cart and status of order is changed
@login_required(login_url='cafe_order:login')
def confirm_order(request,id):
    order = Order.objects.get(id=int(id))
    order.order_status = Order.STATUS[1][0]
    order.save()
    # return (f"Do you want to confirm this that item? {id}")
    return redirect('cafe_order:home')

#This view renders the list of confirmed order which status are 'delivery taken'
@login_required(login_url='cafe_order:login')
def confirmed_order(request):

    order = Order.objects.filter(customer_id=Customer.objects.get(customer_email__iregex=f'{request.user}+@.+'),order_status = Order.STATUS[1][0])
    order_foods = OrderFoods.objects.filter(order_id__customer_id=Customer.objects.get(customer_email__iregex=f'{request.user}+@.+'),
                                            order_id__order_status = Order.STATUS[1][0]                                         
                                            ).select_related('order_id','food_id')

    if len(order)>0:
        context = {
            'order_id': order,
            'order_foods':order_foods,

        }
    else:
        context = {
            'order_foods':order_foods,
            'order_id' : None
        }
    return render(request, 'cafe_order/customer_confirmed_orders.html',context=context)


# This view lists the previous orders' informations of customer
@login_required(login_url='cafe_order:login')
def list_confirmed_orders(request):
    orders = Order.objects.filter(customer_id__customer_email__iregex=f'{request.user}+@.+')\
    .exclude(order_status__in = [Order.STATUS[0][0],Order.STATUS[1][0]])\
    .values('orderfoods__order_id')\
    .annotate(total_foods=Count('orderfoods__food_id__food_name'), price=Sum('orderfoods__food_id__food_price')) \
    .values() \
    .order_by('order_recieved_date')
    if orders:
        order_dict = {}
        for x in orders:

            order_dict[x['id']]={
                'order_recieved_date':x['order_recieved_date'],
                'order_status': x['order_status'],
                'total_foods': x['total_foods'],
                'price': x['price']
            }
    else:
        order_dict = {}
    
    context = {
        'order_dict': order_dict
    }
    return render(request, 'cafe_order/customer_previous_orders.html',context)

Cafe/cafe_order/templates/cafe_order/customer_active_orders.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Cart</title>
    <style>
        p {
            font-size: 20px;
        }
    </style>
</head>

<body>
    <div class="container mt-5">
        <div class="d-flex justify-content-end">
            <div>
                <a class="hello-msg" href="{% url 'cafe_order:logout' %}">Logout</a>
                <a class="hello-msg" href="{% url 'cafe_order:home' %}">Home</a>
            </div>
        </div>
        <div class="d-flex justify-content-center">
            <div>
                {% csrf_token %}
                hello {{request.user}} <br>
                {%for food in order_foods%}
                <p>Food Name:{{food.food_id.food_name}}</p>
                <p>Price: {{food.food_id.food_price}}</p>
                <p>Status: {{food.order_id.order_status}}</p>
                <p>Recieved Date: {{food.order_id.order_recieved_date|date:"M d, Y"}}</p>
                <a href="{% url 'cafe_order:delete_food' id=food.id %}">
                    <button class="btn btn-primary" type="submit">Delete from cart</button>
                </a><br>

                {%endfor%}
                {%if order_id and order_foods%}
                <a href="{% url 'cafe_order:confirm_order' id=order_id %}">
                    <button class="mr-2 btn btn-primary" type="submit">Confirm Order</button>
                </a>
                {%else%}
                <p>You don't have any item on cart. Would you like to add some?</p>
                <a href="{% url 'cafe_order:home'%}">
                    <button class="btn btn-primary" type="submit">Return Home</button>
                </a><br>
                {%endif%}


            </div>
        </div>
    </div>
</body>

Cafe/cafe_order/templates/cafe_order/customer_confirmed_orders.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Orders</title>
    <style>
        p {
            font-size: 20px;
        }
    </style>
</head>

<body>
    {% csrf_token %}
    {% load my_templatetag %}
    {{request.user}} <br>

    <br><br>
    <div class="container mt-5">
        <div class="d-flex justify-content-end">
            <div>
                <a class="hello-msg" href="{% url 'cafe_order:logout' %}">Logout</a>
                <a class="hello-msg" href="{% url 'cafe_order:home' %}">Home</a>
            </div>
        </div>
        <div class="d-flex justify-content-center">
            <div>
                {%for order in order_id%}
                <h1>Order id: {{order.id}}</h1>
                <p>Order Status: {{order.order_status}}</p>
                {%for food in order_foods|get_foods:order.id%}
                <p>Food Name:{{food.food_id.food_name}}</p>
                <p>Price: {{food.food_id.food_price}}</p>
                {%endfor%}
                {%endfor%}
            </div>
        </div>
    </div>
</body>

</html>

Cafe/cafe_order/templates/cafe_order/customer_home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Home</title>
    <style>
        p {
            font-size: 20px;
        }
    </style>
</head>

<body>
    {% csrf_token %}
    <div class="container mt-5">
        <div class="d-flex justify-content-end">
            <div>
                <a class="hello-msg" href="{% url 'cafe_order:logout' %}">Logout</a>
                <a class="hello-msg" href="{% url 'cafe_order:home' %}">Home</a>
            </div>
        </div>
        <div class="d-flex justify-content-center">
            
            <div>
                {{request.user}} <br>
                <a href="{% url 'cafe_order:list_orders' %}">
                    <button type="submit">My Cart</button>
                </a><br>
                <a href="{% url 'cafe_order:confirmed_order' %}">
                    <button type="submit">My Orders</button>
                </a><br>
                <a href="{% url 'cafe_order:list_confirmed_orders' %}">
                    <button type="submit">My Previous Orders</button>
                </a><br>
                {%for food in foods%}
                <h1> The {{food.food_name}}</h1>
                <p>{{food.food_description|lower}}</p>
                <p>Price: {{food.food_price}}$</p>
                <a href="{% url 'cafe_order:create_order' id=food.id %}">
                    <button type="submit">Add to cart</button>
                </a><br>
                {%endfor%}
            </div>
        </div>
    </div>
</body>

</html>

Cafe/cafe_order/templates/cafe_order/customer_login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Login</title>
    <style>
        label{
            display:block
        }
        input{
            border: 1px solid black;
            border-radius: 5px;
            padding:5px
        }
       input[type=submit] {
            width:100%
        }
        .center{
             position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="center">
    <form action="{% url "cafe_order:login" %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Gönder"/>
    </form>
      </div>
    </div>
</body>

</html>

Cafe/cafe_order/templates/cafe_order/customer_previous_orders.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Previous Orders</title>
    <style>
        p {
            font-size: 20px;
        }
    </style>
</head>

<body>
    <div class="container mt-5">
        <div class="d-flex justify-content-end">
            <div>
                <a class="hello-msg" href="{% url 'cafe_order:logout' %}">Logout</a>
                <a class="hello-msg" href="{% url 'cafe_order:home' %}">Home</a>
            </div>
        </div>
        <div class="d-flex justify-content-center">
            <div>
                {% csrf_token %}
                {{request.user}} <br>
                {%for order_id, order_elements in order_dict.items%}
                <h1>Order id: {{order_id}}</h1>
                <p>Total Foods: {{order_elements.total_foods}}</p>
                <p>Order Price:{{order_elements.price}}</p>
                <p>Status: {{order_elements.order_status}}</p>
                <p>Recieved Date: {{order_elements.order_recieved_date|date:"M d, Y"}}</p>

                {%endfor%}


            </div>
        </div>
    </div>
</body>

Cafe/cafe_order/templates/cafe_order/customer_register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Register</title>
    <style>
        label {
            display: block
        }

        input {
            border: 1px solid black;
            border-radius: 5px;
            padding: 5px
        }

        input[type=submit] {
            width: 100%
        }

        .center {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="center">
            <form action="{% url 'cafe_order:register' %}" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Gönder" />
        </div>
    </div>
    </form>
</body>

</html>

Cafe/cafe_order/templates/cafe_order/welcome.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Welcome</title>
    <style>
        label {
            display: block
        }

        input {
            border: 1px solid black;
            border-radius: 5px;
            padding: 5px
        }

        input[type=submit] {
            width: 100%
        }

        .center {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }
    </style>
    <title>Document</title>
</head>

<body>

    <div class="container">
        <div class="center">
            <h1>WELCOME CAFE X</h1>
            <a class="hello-msg" href="{% url 'cafe_order:login' %}">LOGIN</a>
            <a class="hello-msg" href="{% url 'cafe_order:register' %}">REGISTER</a>
        </div>
    </div>
</body>

</html>